server:
  port: 8001
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        '[format_sql]'
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: C##SPRING
    password: SPRING
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    hikari:
      auto-commit: false
  jpa:
    show-sql: true
    generate-ddl: false
    database: oracle
    properties:
      hibernate:
        '[format_sql]'
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
